# 🚀 gha: 0-Effort Universal Installer (PowerShell)
# 100% Sandboxed - 0% Modifications to existing project files.
$ErrorActionPreference = "Stop"

if (-not (Test-Path "init")) { New-Item -ItemType Directory -Force -Path "init" | Out-Null }
if (-not (Test-Path "gradle\wrapper")) { New-Item -ItemType Directory -Force -Path "gradle\wrapper" | Out-Null }

# 1. Scaffold minimal settings.gradle.kts ONLY if no settings file exists (Scenario 1)
if ((-not (Test-Path "settings.gradle.kts")) -and (-not (Test-Path "settings.gradle"))) {
    $folderName = Split-Path -Path $PWD -Leaf
    Write-Host "📥 Creating settings.gradle.kts (rootProject.name = '$folderName')..." -ForegroundColor Cyan
    @'
// Generated by gha - Safe to delete during uninstall
pluginManagement {
    repositories {
        mavenLocal()
        mavenCentral()
        gradlePluginPortal()
    }
}
plugins {
    id("org.gradle.toolchains.foojay-resolver-convention") version "1.0.0"
}
'@ + "`nrootProject.name = `"$folderName`"" | Out-File -Encoding utf8 "settings.gradle.kts"
}

# 2. Scaffold minimal build.gradle.kts if missing
if ((-not (Test-Path "build.gradle.kts")) -and (-not (Test-Path "build.gradle"))) {
    Write-Host "📥 Creating build.gradle.kts..." -ForegroundColor Cyan
    @'
// Generated by gha - Safe to delete during uninstall
plugins {
    `kotlin-dsl`
}
'@ | Out-File -Encoding utf8 "build.gradle.kts"
}

if (-not $env:GHA_REPO) {
    $GHA_REPO = try { git config gha.repo } catch { $null }
    if (-not $GHA_REPO) { $GHA_REPO = "intellibitz/gha" }
} else {
    $GHA_REPO = $env:GHA_REPO
}

# 3. Download or refresh init script
Invoke-WebRequest -Uri "https://raw.githubusercontent.com/$GHA_REPO/main/init/gha.init.gradle.kts" -OutFile "init\gha.init.gradle.kts" -ErrorAction SilentlyContinue

# 4. Bootstrap Gradle wrapper if missing
if (-not (Test-Path ".\gradlew.bat")) {
    Write-Host "📥 Bootstrapping Gradle wrapper..." -ForegroundColor Cyan
    Invoke-WebRequest -Uri "https://raw.githubusercontent.com/$GHA_REPO/main/gradlew" -OutFile "gradlew" -ErrorAction SilentlyContinue
    Invoke-WebRequest -Uri "https://raw.githubusercontent.com/$GHA_REPO/main/gradlew.bat" -OutFile "gradlew.bat" -ErrorAction SilentlyContinue
    Invoke-WebRequest -Uri "https://raw.githubusercontent.com/$GHA_REPO/main/gradle/wrapper/gradle-wrapper.properties" -OutFile "gradle\wrapper\gradle-wrapper.properties" -ErrorAction SilentlyContinue
    Invoke-WebRequest -Uri "https://raw.githubusercontent.com/$GHA_REPO/main/gradle/wrapper/gradle-wrapper.jar" -OutFile "gradle\wrapper\gradle-wrapper.jar" -ErrorAction SilentlyContinue
}

# 5. Fetch latest ghai launchers
Write-Host "📥 Fetching latest ghai launcher script..." -ForegroundColor Cyan
Invoke-WebRequest -Uri "https://raw.githubusercontent.com/$GHA_REPO/main/ghai.bat" -OutFile "ghai.bat" -ErrorAction SilentlyContinue
Invoke-WebRequest -Uri "https://raw.githubusercontent.com/$GHA_REPO/main/ghai" -OutFile "ghai" -ErrorAction SilentlyContinue

# 6. Delegate to ghaInit
.\gradlew.bat -Dgradle.user.home=.gha/gradle-user-home --init-script init/gha.init.gradle.kts ghaInit $args
