#!/usr/bin/env bash
# 🚀 gha: 0-Effort Universal Installer
# 100% Sandboxed - 0% Modifications to existing project files.
set -e

mkdir -p init gradle/wrapper

# 1. Scaffold minimal settings.gradle.kts ONLY if no settings file exists (Scenario 1: Empty folder)
if [ ! -f "settings.gradle.kts" ] && [ ! -f "settings.gradle" ]; then
    PROJECT_NAME="$(basename "$PWD")"
    echo "📥 Creating settings.gradle.kts for gha workspace..."
    cat << 'EOF' > settings.gradle.kts
// Generated by gha - Safe to delete during uninstall
pluginManagement {
    repositories {
        mavenLocal()
        mavenCentral()
        gradlePluginPortal()
    }
}
plugins {
    id("org.gradle.toolchains.foojay-resolver-convention") version "1.0.0"
}
EOF
    echo "rootProject.name = \"$PROJECT_NAME\"" >> settings.gradle.kts
fi

# 2. Scaffold minimal build.gradle.kts ONLY if no build file exists
if [ ! -f "build.gradle.kts" ] && [ ! -f "build.gradle" ]; then
    echo "📥 Creating build.gradle.kts for gha workspace..."
    cat << 'EOF' > build.gradle.kts
// Generated by gha - Safe to delete during uninstall
plugins {
    `kotlin-dsl`
}
EOF
fi

# 3. Download or refresh init script (The heart of gha "extension" logic)
curl -sSL "https://raw.githubusercontent.com/intellibitz/gha/main/init/gha.init.gradle.kts" -o "init/gha.init.gradle.kts" 2>/dev/null || true

# 4. Bootstrap Gradle wrapper if missing
if [ ! -f "gradlew" ]; then
    echo "📥 Bootstrapping Gradle wrapper (gradlew)..."
    curl -sSL "https://raw.githubusercontent.com/intellibitz/gha/main/gradlew" -o "gradlew" 2>/dev/null || true
    curl -sSL "https://raw.githubusercontent.com/intellibitz/gha/main/gradlew.bat" -o "gradlew.bat" 2>/dev/null || true
    curl -sSL "https://raw.githubusercontent.com/intellibitz/gha/main/gradle/wrapper/gradle-wrapper.properties" -o "gradle/wrapper/gradle-wrapper.properties" 2>/dev/null || true
    curl -sSL "https://raw.githubusercontent.com/intellibitz/gha/main/gradle/wrapper/gradle-wrapper.jar" -o "gradle/wrapper/gradle-wrapper.jar" 2>/dev/null || true
fi

chmod +x gradlew 2>/dev/null || true

# 5. Fetch and update ./ghai executable launcher
echo "📥 Fetching latest ghai launcher script..."
curl -sSL "https://raw.githubusercontent.com/intellibitz/gha/main/ghai" -o "ghai" 2>/dev/null || true
curl -sSL "https://raw.githubusercontent.com/intellibitz/gha/main/ghai.bat" -o "ghai.bat" 2>/dev/null || true
chmod +x ghai 2>/dev/null || true

# 6. Update .gitignore for Invisible Integration (0 side effects)
if [ -f ".gitignore" ]; then
    if ! grep -q "# gha: Git, GitHub & Gradle Automation" ".gitignore"; then
        echo "   ➕ Updating .gitignore for invisible gha integration..."
        cat << 'EOF' >> .gitignore

# gha: Git, GitHub & Gradle Automation (Invisible Sandbox)
.gha/
ghai
ghai.bat
init/gha.init.gradle.kts
EOF
    fi
fi

# 7. Delegate to ghaInit to finalize the sandbox
exec ./gradlew -Dgradle.user.home=.gha/gradle-user-home --init-script init/gha.init.gradle.kts ghaInit "$@"
