package cc.thevar.gha

import org.gradle.api.tasks.TaskAction
import org.gradle.work.DisableCachingByDefault
import java.io.File

@DisableCachingByDefault(because = "Removes gha sandbox, runner scripts, and workflows cleanly")
abstract class GhaUninstallTask : GhaTask() {

    @TaskAction
    fun execute() {
        val rootDir = projectRootDir.get().asFile
        logger.lifecycle("🧹 [GHA Uninstall] Executing 100% Kotlin cleanup across root & subprojects...")

        // 1. Remove .gha sandbox directory
        val ghaDir = File(rootDir, ".gha")
        if (ghaDir.exists()) {
            ghaDir.deleteRecursively()
            logger.lifecycle("   🗑️ Removed .gha/ sandbox directory")
        }

        // 2. Remove init/gha.init.gradle.kts
        val initScript = File(rootDir, "init/gha.init.gradle.kts")
        if (initScript.exists()) {
            initScript.delete()
            logger.lifecycle("   🗑️ Removed init/gha.init.gradle.kts")
        }

        // 3. Remove .github/workflows/gha.yml
        val workflowFile = File(rootDir, ".github/workflows/gha.yml")
        if (workflowFile.exists()) {
            workflowFile.delete()
            logger.lifecycle("   🗑️ Removed .github/workflows/gha.yml")
        }

        // 4. Remove local launcher scripts
        val ghaiScript = File(rootDir, "ghai")
        if (ghaiScript.exists()) {
            ghaiScript.delete()
            logger.lifecycle("   🗑️ Removed ghai launcher script")
        }

        val ghaiBat = File(rootDir, "ghai.bat")
        if (ghaiBat.exists()) {
            ghaiBat.delete()
            logger.lifecycle("   🗑️ Removed ghai.bat launcher script")
        }

        // 5. Remove user symlink if present
        val userSymlink = File(System.getProperty("user.home"), ".local/bin/ghai")
        if (userSymlink.exists()) {
            userSymlink.delete()
            logger.lifecycle("   🗑️ Removed ~/.local/bin/ghai symlink")
        }

        // 6. Safely remove settings.gradle.kts and build.gradle.kts ONLY if they were gha-generated
        val settingsFile = File(rootDir, "settings.gradle.kts")
        if (settingsFile.exists() && settingsFile.readText().contains("Generated by gha")) {
            settingsFile.delete()
            logger.lifecycle("   🗑️ Removed gha-generated settings.gradle.kts")
        }

        val buildFile = File(rootDir, "build.gradle.kts")
        if (buildFile.exists() && buildFile.readText().contains("Generated by gha")) {
            buildFile.delete()
            logger.lifecycle("   🗑️ Removed gha-generated build.gradle.kts")
        }

        // 7. Cleanup .gitignore entries
        val gitignore = File(rootDir, ".gitignore")
        if (gitignore.exists()) {
            val content = gitignore.readText()
            if (content.contains("# gha: Git, GitHub & Gradle Automation")) {
                val lines = gitignore.readLines()
                val newLines = mutableListOf<String>()
                var skip = false
                for (line in lines) {
                    if (line.contains("# gha: Git, GitHub & Gradle Automation")) {
                        skip = true
                        continue
                    }
                    if (skip) {
                        if (line.isBlank() || line.startsWith(".gha/") || line.startsWith("ghai") || line.startsWith("ghai.bat") || line.startsWith("init/gha.init.gradle.kts")) {
                            continue
                        } else {
                            skip = false
                        }
                    }
                    newLines.add(line)
                }
                gitignore.writeText(newLines.joinToString("\n") + "\n")
                logger.lifecycle("   🗑️ Removed gha entries from .gitignore")
            }
        }

        logger.lifecycle("✨ [GHA Uninstall] gha removed completely with 0 side effects to user files!")
    }
}
